//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_Banner
    {
        public int BAN_Id { get; set; }
        public string BAN_Descripcion { get; set; }
        public string BAN_HTML { get; set; }
        public Nullable<bool> BAN_Activa { get; set; }
        public Nullable<int> STS_Id { get; set; }
        public string BAN_Imagen { get; set; }
        public Nullable<System.DateTime> BAN_Date { get; set; }
    
        public virtual STS_Status STS_Status { get; set; }
    }
}
