//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img_Tipos
    {
        public Img_Tipos()
        {
            this.DOC_Documentos = new HashSet<DOC_Documentos>();
        }
    
        public int Img_Type { get; set; }
        public string Img_Descripcion { get; set; }
    
        public virtual ICollection<DOC_Documentos> DOC_Documentos { get; set; }
    }
}
