//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSV_TipoServicio
    {
        public TSV_TipoServicio()
        {
            this.SER_Servicios = new HashSet<SER_Servicios>();
        }
    
        public int TSV_Id { get; set; }
        public string TSV_Descripcion { get; set; }
    
        public virtual ICollection<SER_Servicios> SER_Servicios { get; set; }
    }
}
