//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAN_Banner> BAN_Banner { get; set; }
        public DbSet<CAT_Categorias> CAT_Categorias { get; set; }
        public DbSet<CLI_Clientes> CLI_Clientes { get; set; }
        public DbSet<COD_CotizacionDetalle> COD_CotizacionDetalle { get; set; }
        public DbSet<COM_Compañia> COM_Compañia { get; set; }
        public DbSet<CON_Contactenos> CON_Contactenos { get; set; }
        public DbSet<COT_Cotizaciones> COT_Cotizaciones { get; set; }
        public DbSet<DOC_Documentos> DOC_Documentos { get; set; }
        public DbSet<IMG_Images> IMG_Images { get; set; }
        public DbSet<Img_Tipos> Img_Tipos { get; set; }
        public DbSet<PRC_PantallaInicial> PRC_PantallaInicial { get; set; }
        public DbSet<PRD_ProductosDetalles> PRD_ProductosDetalles { get; set; }
        public DbSet<PRO_Productos> PRO_Productos { get; set; }
        public DbSet<PTC_Patrocinadores> PTC_Patrocinadores { get; set; }
        public DbSet<SER_Servicios> SER_Servicios { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TSV_TipoServicio> TSV_TipoServicio { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
