//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COD_CotizacionDetalle
    {
        public int CED_Id { get; set; }
        public int COD_Id { get; set; }
        public int PRO_Id { get; set; }
        public int COD_Cantidad { get; set; }
    
        public virtual COT_Cotizaciones COT_Cotizaciones { get; set; }
        public virtual PRO_Productos PRO_Productos { get; set; }
    }
}
