//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COT_Cotizaciones
    {
        public COT_Cotizaciones()
        {
            this.COD_CotizacionDetalle = new HashSet<COD_CotizacionDetalle>();
        }
        [Display(Name = "Código")]
        public int COT_Id { get; set; }
        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Mensaje")]
        public string COT_Descripcion { get; set; }
        public Nullable<System.DateTime> COT_Fecha { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Nombre")]
        public string COT_Nombre { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Telefóno")]
        public string COT_Telefono { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Correo Electrónico")]
        public string COT_Email { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Celular")]
        public string COT_Celular { get; set; }
        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 7)]
        [Display(Name = "Más información")]
        public string COT_Mensaje { get; set; }
        [Required]
        [Display(Name = "Estatus")]
        public int STS_Id { get; set; }

        public virtual ICollection<COD_CotizacionDetalle> COD_CotizacionDetalle { get; set; }
        public virtual STS_Status STS_Status { get; set; }
    }
}
