//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COT_Cotizaciones
    {
        public COT_Cotizaciones()
        {
            this.COD_CotizacionDetalle = new HashSet<COD_CotizacionDetalle>();
        }
    
        public int COT_Id { get; set; }
        public string COT_Descripcion { get; set; }
        public Nullable<System.DateTime> COT_Fecha { get; set; }
        public string COT_Nombre { get; set; }
        public string COT_Telefono { get; set; }
        public string COT_Email { get; set; }
        public string COT_Celular { get; set; }
        public string COT_Mensaje { get; set; }
        public int STS_Id { get; set; }
    
        public virtual ICollection<COD_CotizacionDetalle> COD_CotizacionDetalle { get; set; }
        public virtual STS_Status STS_Status { get; set; }
    }
}
