//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_Documentos
    {
        public int Doc_Id { get; set; }
        public Nullable<int> Img_Type { get; set; }
        public Nullable<System.DateTime> Doc_Fecha { get; set; }
        public string Doc_Url { get; set; }
    
        public virtual Img_Tipos Img_Tipos { get; set; }
    }
}
