//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG_Images
    {
        public int IMG_Id { get; set; }
        public string IMG_Path { get; set; }
        public string IMG_Name { get; set; }
        public Nullable<System.DateTime> IMG_Date { get; set; }
    }
}
