//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_PantallaInicial
    {
        public int PRC_Id { get; set; }
        public string PRC_Text { get; set; }
        public string PRC_Descripcion { get; set; }
        public string PRC_Html { get; set; }
        public string PRC_Imagen { get; set; }
        public Nullable<int> STS_Id { get; set; }
        public Nullable<System.DateTime> PRC_Date { get; set; }
    
        public virtual STS_Status STS_Status { get; set; }
    }
}
