//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_ProductosDetalles
    {
        public int PRD_Id { get; set; }
        public int PRO_Id { get; set; }
        public string PRD_Descripcion { get; set; }
        public string PRD_Html { get; set; }
        public string PRD_Images { get; set; }
        public Nullable<System.DateTime> PRD_Date { get; set; }
    }
}
