//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_Productos
    {
        public PRO_Productos()
        {
            this.COD_CotizacionDetalle = new HashSet<COD_CotizacionDetalle>();
        }
    
        public int PRO_Id { get; set; }
        public int STS_Id { get; set; }
        public int CAT_Id { get; set; }
        public string PRO_Nombre { get; set; }
        public string PRO_Descripcion { get; set; }
        public string PRO_HTML { get; set; }
        public Nullable<bool> PRO_IsBanner { get; set; }
        public string PRO_Image { get; set; }
        public Nullable<System.DateTime> PRO_Date { get; set; }
    
        public virtual CAT_Categorias CAT_Categorias { get; set; }
        public virtual ICollection<COD_CotizacionDetalle> COD_CotizacionDetalle { get; set; }
        public virtual STS_Status STS_Status { get; set; }
    }
}
