//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PTC_Patrocinadores
    {
        public int PTC_Id { get; set; }
        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [Display(Name = "Nombre de Patrocinador")]
        public string PTC_Nombre { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [Display(Name = "Descripción")]
        public string PTC_Descripcion { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [Display(Name = "Dirección Web del Patrocinador")]
        public string PTC_Url { get; set; }
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [Display(Name = "Imagen del Patrocinador")]
        public string PTC_Imagen { get; set; }
        [Required]
        [Display(Name = "Estatus")]
        public int STS_Id { get; set; }

        public virtual STS_Status STS_Status { get; set; }
    }
}
