//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_Patrocinadores
    {
        public int PTC_Id { get; set; }
        public string PTC_Nombre { get; set; }
        public string PTC_Descripcion { get; set; }
        public string PTC_Url { get; set; }
        public string PTC_Imagen { get; set; }
        public int STS_Id { get; set; }
    
        public virtual STS_Status STS_Status { get; set; }
    }
}
