//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroGanSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STS_Status
    {
        public STS_Status()
        {
            this.BAN_Banner = new HashSet<BAN_Banner>();
            this.COT_Cotizaciones = new HashSet<COT_Cotizaciones>();
            this.NEW_Noticias = new HashSet<NEW_Noticias>();
            this.PRC_PantallaInicial = new HashSet<PRC_PantallaInicial>();
            this.PRO_Productos = new HashSet<PRO_Productos>();
            this.PTC_Patrocinadores = new HashSet<PTC_Patrocinadores>();
            this.SER_Servicios = new HashSet<SER_Servicios>();
        }
    
        public int STS_Id { get; set; }
        public string STS_Descripcion { get; set; }
    
        public virtual ICollection<BAN_Banner> BAN_Banner { get; set; }
        public virtual ICollection<COT_Cotizaciones> COT_Cotizaciones { get; set; }
        public virtual ICollection<NEW_Noticias> NEW_Noticias { get; set; }
        public virtual ICollection<PRC_PantallaInicial> PRC_PantallaInicial { get; set; }
        public virtual ICollection<PRO_Productos> PRO_Productos { get; set; }
        public virtual ICollection<PTC_Patrocinadores> PTC_Patrocinadores { get; set; }
        public virtual ICollection<SER_Servicios> SER_Servicios { get; set; }
    }
}
